### ISSUE TITLE
Tracking: IBC integration

### ISSUE THREAD

**Issue by yito88** [namada-net/namada#78]
Related to anoma/anoma#866 

### IBC native VP
- [x] Validate IBC-related data [anoma/anoma#327]
- [ ] ~~Set and validate "clients/{identifier}/connections"~~ [#42] = > 1.1
- [ ] ~~Misbehavior~~ [#80] => 1.1
- [x] Add a native VP to check escrow/unescrow/burn/mint token in a token transfer [anoma/anoma#823]
- [x] Support multitoken [#132]
- [x] Fix MsgTimeoutOnClose and give the channel proof
    - [x] Fix ibc-rs' message conversion (ibc-rs v0.19)
    - [x] Give the channel proof when TimeoutOnClose [#260]

### Proof
- [x] Modify MerkleTree for ICS23 proof verification [anoma/anoma#671]
- [x] Query data with the proof [anoma/anoma#498]
- [x] SMT proof for non-existence is incompatible with ICS23 crate [#92]

### IBC-related transaction
- [x] [IBC transaction](https://github.com/anoma/anoma/blob/f6e78278608aaef253617885bb7ef95a50057268/wasm/wasm_source/src/lib.rs#L219-L233) calls just `dispatch` function with data which is an encoded IBC message
- [x] Handling functions for a transaction [anoma/anoma#411]
  - [x] IBC-related operations are implemented in `IbcActions`[anoma/anoma#720]
  - [x] Implement `IbcActions` for `vm_env` (which calls just `vm_env::imports::read_bytes`, `write_bytes` etc.) [anoma/anoma#823]
  - [x] IBC message as a transaction data [anoma/anoma#719]
  - [x] ~~[BLOCKED]~~ Building IBC transaction with WASM
      - Need the next release version v0.12.0 of `ibc-rs` anoma/anoma#926
        - Tried with ibc-rs master -> IBC transaction could be built (some fixes are needed to update for v0.12.0)
- [x] IBC ack and FungibleTokenData are incompatible with ibc-go [#101] 
    - [x] Update ibc-rs to v0.14 for serialization [#260]
    - [x] Fix IBC ack and FungibleTokenData [#261]

### ICS20 FungibleTokenTransfer
- [x] sending/receiving tokens [anoma/anoma#823]
- [x] Relay transfer with multitoken for ICS20 [#117]

### Others
- [x] Emit an IBC event [anoma/anoma#480]
- [x] Update `ibc-rs` to v0.11.0 to call the latest proof verification functions [anoma/anoma#863]
- [x] Fix the hash header for consensus state proof [#298]
- [x] Fix `response.consensus_param_updates` when `update_epoch` for tendermint `block_results`
    - Fix tendermint-rs [heliaxdev/tendermint-rs#4]

### Relayer (in [heliaxdev/ibc-rs](https://github.com/heliaxdev/ibc-rs))
- Add ChainEndpoint of Anoma
  - [Rebased and fixed the prototype relayer with the latest ibc-rs](https://github.com/heliaxdev/ibc-rs/tree/yuji/rebase_v0.23.5_anoma)
  - Updated: https://github.com/heliaxdev/ibc-rs/tree/yuji/v0.14.0_anoma [ibc-rs e2e tests passed]
- Relayer for Namada
  - https://github.com/heliaxdev/ibc-rs/tree/yuji/v0.14.0_namada (for Namada with Tendermint 0.37)

## Integration test
- [x] [Tests with vm_host_env](https://github.com/anoma/namada/blob/master/tests/src/vm_host_env/mod.rs)

## E2E test
- [x] Add e2e tests for IBC between two Namada chains without a relayer [#79]
- [x] Add e2e tests for between Anoma and other chains
    - ibc-rs e2e tests with Gaia ~~(forked for SMT proofs)~~ passed

**Comment by yito88** [comment]
The first integration tasks were completed.
